package wsdlServices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-01-15T15:34:19.907+01:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EmailValidatorService",
                  wsdlLocation = "https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/EmailValidator?wsdl",
                  targetNamespace = "http://emailValidator.milan.jovic.dmi.uns.ac.rs/")
public class EmailValidatorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://emailValidator.milan.jovic.dmi.uns.ac.rs/", "EmailValidatorService");
    public final static QName EmailValidatorPort = new QName("http://emailValidator.milan.jovic.dmi.uns.ac.rs/", "EmailValidatorPort");
    static {
        URL url = null;
        try {
            url = new URL("https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/EmailValidator?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmailValidatorService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/EmailValidator?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmailValidatorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmailValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmailValidatorService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EmailValidatorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmailValidatorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmailValidatorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EmailValidatorRemote
     */
    @WebEndpoint(name = "EmailValidatorPort")
    public EmailValidatorRemote getEmailValidatorPort() {
        return super.getPort(EmailValidatorPort, EmailValidatorRemote.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmailValidatorRemote
     */
    @WebEndpoint(name = "EmailValidatorPort")
    public EmailValidatorRemote getEmailValidatorPort(WebServiceFeature... features) {
        return super.getPort(EmailValidatorPort, EmailValidatorRemote.class, features);
    }

}
