package wsdlServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-01-15T15:34:19.886+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://emailValidator.milan.jovic.dmi.uns.ac.rs/", name = "EmailValidatorRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface EmailValidatorRemote {

    @WebMethod
    @RequestWrapper(localName = "validateEmail", targetNamespace = "http://emailValidator.milan.jovic.dmi.uns.ac.rs/", className = "wsdlServices.ValidateEmail")
    @ResponseWrapper(localName = "validateEmailResponse", targetNamespace = "http://emailValidator.milan.jovic.dmi.uns.ac.rs/", className = "wsdlServices.ValidateEmailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean validateEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
