package mojws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-01-14T19:46:35.050+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://webServices.statelessBeans/", name = "FutureConf")
@XmlSeeAlso({ObjectFactory.class})
public interface FutureConf {

    @WebMethod
    @RequestWrapper(localName = "getFutureConferences", targetNamespace = "http://webServices.statelessBeans/", className = "mojws.GetFutureConferences")
    @ResponseWrapper(localName = "getFutureConferencesResponse", targetNamespace = "http://webServices.statelessBeans/", className = "mojws.GetFutureConferencesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<mojws.Conference> getFutureConferences(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
