package mojws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-01-14T19:46:35.073+01:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "FutureConfService",
                  wsdlLocation = "http://localhost:8080/KonferencijaEJB/FutureConf?wsdl",
                  targetNamespace = "http://webServices.statelessBeans/")
public class FutureConfService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webServices.statelessBeans/", "FutureConfService");
    public final static QName FutureConfPort = new QName("http://webServices.statelessBeans/", "FutureConfPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/KonferencijaEJB/FutureConf?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FutureConfService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/KonferencijaEJB/FutureConf?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FutureConfService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FutureConfService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FutureConfService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FutureConfService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FutureConfService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FutureConfService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FutureConf
     */
    @WebEndpoint(name = "FutureConfPort")
    public FutureConf getFutureConfPort() {
        return super.getPort(FutureConfPort, FutureConf.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FutureConf
     */
    @WebEndpoint(name = "FutureConfPort")
    public FutureConf getFutureConfPort(WebServiceFeature... features) {
        return super.getPort(FutureConfPort, FutureConf.class, features);
    }

}
